<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="7"
           failures="2"
           errors="0"
           skipped="0"
           time="0.017">
  <properties />
            <testcase name="first_testcase" time="0.005" classname="testNGDemo.TestScenario5">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1590)
  org.testng.Assert.assertEqualsImpl(Assert.java:150)
  org.testng.Assert.assertEquals(Assert.java:132)
  org.testng.Assert.assertEquals(Assert.java:1079)
  org.testng.Assert.assertEquals(Assert.java:1043)
  org.testng.Assert.assertEquals(Assert.java:1089)
  testNGDemo.TestScenario5.first_testcase(TestScenario5.java:13)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
  org.testng.TestRunner.privateRun(TestRunner.java:741)
  org.testng.TestRunner.run(TestRunner.java:616)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
  org.testng.SuiteRunner.run(SuiteRunner.java:312)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
  org.testng.TestNG.runSuites(TestNG.java:1112)
  org.testng.TestNG.run(TestNG.java:1079)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
      </failure>

          </testcase>
            <testcase name="sixth_testcase" time="0.003" classname="testNGDemo.TestScenario5">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1590)
  org.testng.Assert.assertEqualsImpl(Assert.java:150)
  org.testng.Assert.assertEquals(Assert.java:132)
  org.testng.Assert.assertEquals(Assert.java:1079)
  org.testng.Assert.assertEquals(Assert.java:1043)
  org.testng.Assert.assertEquals(Assert.java:1089)
  testNGDemo.TestScenario5.sixth_testcase(TestScenario5.java:44)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
  org.testng.TestRunner.privateRun(TestRunner.java:741)
  org.testng.TestRunner.run(TestRunner.java:616)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
  org.testng.SuiteRunner.run(SuiteRunner.java:312)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
  org.testng.TestNG.runSuites(TestNG.java:1112)
  org.testng.TestNG.run(TestNG.java:1079)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="forth_testcase" time="0.001" classname="testNGDemo.TestScenario5" />
                <testcase name="third_testcase" time="0.002" classname="testNGDemo.TestScenario5" />
                <testcase name="fifth_testcase" time="0.002" classname="testNGDemo.TestScenario5" />
                <testcase name="seventh_testcase" time="0.001" classname="testNGDemo.TestScenario5" />
                <testcase name="second_testcase" time="0.003" classname="testNGDemo.TestScenario5" />
      
</testsuite>
